// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char THING_ID[] = "THING_ID";
const char DEVICE_LOGIN_NAME[]  = "DEVICE_NAME";

const char SSID[]               = "WiFi_Name";    // Network SSID (name)
const char PASS[]               = "WiFi_Password";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "Device_Key";    // Secret device password

void onLightsChange();

CloudColoredLight lights;

void initProperties(){
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lights, READWRITE, ON_CHANGE, onLightsChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
