// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

#define SECRET_SSID "WiFi_Name"
#define SECRET_PASS "WiFi_Password"
#define SECRET_DEVICE_KEY "IoT_Device_Key"

const char THING_ID[]           = "IoT_Thing_Id";
const char DEVICE_LOGIN_NAME[]  = "IoT_Device_Name";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onNeopixelsChange();

CloudColoredLight neopixels;

void initProperties(){
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(neopixels, READWRITE, ON_CHANGE, onNeopixelsChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
